// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYnyT49C_rqkSoj6uw5tO84VXQw1oaGaI',
    appId: '1:858428334307:web:92352da3ece16df87325d6',
    messagingSenderId: '858428334307',
    projectId: 'ditonton-5d28a',
    authDomain: 'ditonton-5d28a.firebaseapp.com',
    storageBucket: 'ditonton-5d28a.appspot.com',
    measurementId: 'G-XW558RTVBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2mbJsr8K9zgQefLIvlDOgSPqGfsgjQyc',
    appId: '1:858428334307:android:d6ce9aa67ba836e77325d6',
    messagingSenderId: '858428334307',
    projectId: 'ditonton-5d28a',
    storageBucket: 'ditonton-5d28a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpthSsb1uLB-FVKn2NxRxaC2aiQI9EVo8',
    appId: '1:858428334307:ios:3b4bc70c5fd699cd7325d6',
    messagingSenderId: '858428334307',
    projectId: 'ditonton-5d28a',
    storageBucket: 'ditonton-5d28a.appspot.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
